// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AutofilladdressController from "./autofilladdress_controller"
application.register("autofilladdress", AutofilladdressController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HiddenController from "./hidden_controller"
application.register("hidden", HiddenController)

import LocationsearchController from "./locationsearch_controller"
application.register("locationsearch", LocationsearchController)

import MapboxController from "./mapbox_controller"
application.register("mapbox", MapboxController)

import MultiselectController from "./multiselect_controller"
application.register("multiselect", MultiselectController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)
