require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes # To always allow #{interpolation}, and reduce fatigue from changing strings

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'

Rails/EnvironmentVariableAccess:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'Guardfile'
    - 'spec/rails_helper.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'

Style/SymbolArray:
  MinSize: 4
  Exclude:
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 20

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
