version: "3"
services:
  db:
    image: postgis/postgis:17-3.5
    volumes:
      - app_db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DOCKERIZED: "true"
      DATABASE_URL: "postgis://postgres:password@db/lokaler_lnu_no_development?pool=5"


volumes:
  app_storage:
    driver: local
  app_db:
    driver: local

  ## Run the following after the server has started for the first time:
  ## docker-compose run web rake db:create db:migrate
