version: '3'
services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: lokaler_lnu_no_production
    ports:
      - "5432:5432"

  cache_db:
    image: postgres:15
    volumes:
      - postgres_cache_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: lokaler_lnu_no_production_cache
    ports:
      - "5433:5432"

  queue_db:
    image: postgres:15
    volumes:
      - postgres_queue_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: lokaler_lnu_no_production_queue
    ports:
      - "5434:5432"

  cable_db:
    image: postgres:15
    volumes:
      - postgres_cable_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: lokaler_lnu_no_production_cable
    ports:
      - "5435:5432"

  web:
    image: lokaler
    depends_on:
      - db
      - cache_db
      - queue_db
      - cable_db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Database configurations that override .env for Docker
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: lokaler_lnu_no_production
      CACHE_DATABASE_HOST: cache_db
      CACHE_DATABASE_PORT: 5432
      CACHE_DATABASE_USERNAME: postgres
      CACHE_DATABASE_PASSWORD: password
      CACHE_DATABASE_NAME: lokaler_lnu_no_production_cache
      QUEUE_DATABASE_HOST: queue_db
      QUEUE_DATABASE_PORT: 5432
      QUEUE_DATABASE_USERNAME: postgres
      QUEUE_DATABASE_PASSWORD: password
      QUEUE_DATABASE_NAME: lokaler_lnu_no_production_queue
      CABLE_DATABASE_HOST: cable_db
      CABLE_DATABASE_PORT: 5432
      CABLE_DATABASE_USERNAME: postgres
      CABLE_DATABASE_PASSWORD: password
      CABLE_DATABASE_NAME: lokaler_lnu_no_production_cable
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      FORCE_SSL: 'false'

volumes:
  postgres_data:
  postgres_cache_data:
  postgres_queue_data:
  postgres_cable_data: