// Flat config. Replaces the old .eslintrc.js, which ESLint 9 stopped reading by
// default and ESLint 10 dropped support for entirely.
//
// Deliberately NOT airbnb-base. That config is unmaintained for flat config, its
// peer range does not overlap ESLint 10, and it could only be loaded through a
// FlatCompat shim. More to the point, ~75% of what it reported here was pure
// formatting (semicolons, quote style, indentation) with no bug-catching value,
// and a chunk of the rest fought idiomatic Stimulus and Rails naming.
//
// What is left is the part that earns its keep: js.configs.recommended catches
// real defects (undefined variables, unused bindings, unreachable code, dupe
// keys), plus a handful of rules below that prevent genuine footguns. Formatting
// is intentionally not linted — that is a formatter's job, not a reviewer's.

import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    ignores: [
      'node_modules/**',
      'app/assets/builds/**',
      'public/**',
      'vendor/**',
      'tmp/**',
      // Static data, not hand-maintained code
      'app/javascript/controllers/search_and_filter/fylker_and_kommuner.js',
      // Auto-generated by ./bin/rails stimulus:manifest:update
      'app/javascript/controllers/index.js',
    ],
  },
  js.configs.recommended,
  {
    files: ['app/javascript/**/*.js'],
    languageOptions: {
      // "latest", not a pinned year: Stimulus controllers use class fields
      // (`static targets = [...]`), which is ES2022. The old config said 2021,
      // so 17 of 28 files failed to parse and were silently never linted.
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      // Signals that a binding is never reassigned, and catches the cases where
      // you thought it was.
      'prefer-const': 'error',
      // var is function-scoped and hoisted; let/const are not.
      'no-var': 'error',
      // == does type coercion, which surprises people. null is exempted so the
      // common `x == null` (null or undefined) idiom still works.
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      // Left-behind debug logging. A warning rather than an error, since
      // console.warn/error are legitimate.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      // Recommended already enables this; widened so a leading underscore marks
      // an argument as deliberately ignored, which is the usual convention for
      // callbacks whose signature you do not control.
      'no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
    },
  },
];
