// Flat config, replacing the old .eslintrc.js.
// ESLint 9 stopped reading .eslintrc by default and ESLint 10 dropped it entirely,
// so the previous config had silently stopped applying.
//
// airbnb-base still ships as an eslintrc-style config, so it is loaded through
// FlatCompat rather than rewritten by hand — this keeps the same rule set the
// project has always used (see CLAUDE.md: "JS: Follows Airbnb base style").

import path from 'path';
import { fileURLToPath } from 'url';
import js from '@eslint/js';
import globals from 'globals';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: path.dirname(fileURLToPath(import.meta.url)),
  recommendedConfig: js.configs.recommended,
});

export default [
  {
    ignores: [
      'node_modules/**',
      'app/assets/builds/**',
      'public/**',
      'vendor/**',
      'tmp/**',
      // Static data, not hand-maintained code
      'app/javascript/controllers/search_and_filter/fylker_and_kommuner.js',
      // Auto-generated by ./bin/rails stimulus:manifest:update
      'app/javascript/controllers/index.js',
    ],
  },
  ...compat.extends('airbnb-base'),
  {
    files: ['app/javascript/**/*.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      globals: {
        ...globals.browser,
      },
    },
    rules: {},
  },
];
