development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: lokaler_lnu_no_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>  # For Heroku only, delete if we are no longer on Heroku
