default: &default
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day

development:
  <<: *default

test:
  adapter: test

staging:
  <<: *default

production:
  <<: *default