default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 512.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
