default: &default
  adapter: postgis # Uses postgis, see guide at https://medium.com/@Evert_Salinas/creating-a-basic-geolocation-search-application-with-postgis-and-rails-part-i-6f7c8985b6da
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_cache: &default_cache
  <<: *default
  adapter: postgresql
  migrations_paths: db/cache_migrate

default_queue: &default_queue
  <<: *default
  adapter: postgresql
  migrations_paths: db/queue_migrate

default_cable: &default_cable
  <<: *default
  adapter: postgresql
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *default
    database: lokaler_lnu_no_development
  cache:
    <<: *default_cache
    database: lokaler_lnu_no_develpment_cache
  queue:
    <<: *default_queue
    database: lokaler_lnu_no_development_queue
  cable:
    <<: *default_cable
    database: lokaler_lnu_no_development_cable

test:
  primary:
    <<: *default
    database: lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>
  cache:
    <<: *default_cache
    database: lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>_cache
  queue:
    <<: *default_queue
    database: lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>_queue

production_database: &production_database
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

production:
  primary:
    <<: *default
    <<: *production_database
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    database: "lokaler_lnu_no_production"
  cache:
    <<: *default_cache
    <<: *production_database
    host: <%= ENV.fetch("CACHE_DATABASE_HOST", "localhost") %>
    database: "lokaler_lnu_no_production_cache"
  queue:
    <<: *default_queue
    <<: *production_database
    host: <%= ENV.fetch("QUEUE_DATABASE_HOST", "localhost") %>
    database: "lokaler_lnu_no_production_queue"
  cable:
    <<: *default_cable
    <<: *production_database
    host: <%= ENV.fetch("CABLE_DATABASE_HOST", "localhost") %>
    database: "lokaler_lnu_no_production_cable"


