default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

postgis: &postgis
  <<: *default
  adapter: postgis

sqlite_cache: &sqlite_cache
  <<: *default
  adapter: sqlite3
  migrations_paths: db/cache_migrate

sqlite_queue: &sqlite_queue
  <<: *default
  adapter: sqlite3
  migrations_paths: db/queue_migrate

sqlite_cable: &sqlite_cable
  <<: *default
  adapter: sqlite3
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *postgis
    database: lokaler_lnu_no_development
  cache:
    <<: *sqlite_cache
    database: storage/lokaler_lnu_no_develpment_cache.sqlite3
  queue:
    <<: *sqlite_queue
    database: storage/lokaler_lnu_no_development_queue.sqlite3
  cable:
    <<: *sqlite_cable
    database: storage/lokaler_lnu_no_development_cable.sqlite3

test:
  primary:
    <<: *postgis
    database: lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>
  cache:
    <<: *sqlite_cache
    database: storage/lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>_cache.sqlite3
  queue:
    <<: *sqlite_queue
    database: storage/lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>_queue.sqlite3

production:
  primary:
    <<: *postgis
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USER", "") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    database: "lokaler_lnu_no_production"
  cache:
    <<: *sqlite_cache
    database: <%= Rails.root.join("storage", "lokaler_lnu_no_production_cache.sqlite3") %>
  queue:
    <<: *sqlite_queue
    database: <%= Rails.root.join("storage", "lokaler_lnu_no_production_queue.sqlite3") %>
  cable:
    <<: *sqlite_cable
    database: <%= Rails.root.join("storage", "lokaler_lnu_no_production_cable.sqlite3") %>


