default: &default
  adapter: postgis # Uses postgis, see guide at https://medium.com/@Evert_Salinas/creating-a-basic-geolocation-search-application-with-postgis-and-rails-part-i-6f7c8985b6da
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lokaler_lnu_no_development

test:
  <<: *default
  # For details on connection pooling, see Rails configuration guide
   # https://guides.rubyonrails.org/configuring.html#database-pooling
  database: lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  # Use explicit connection details for the database
  database: <%= ENV.fetch('POSTGRES_DB') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  port: <%= ENV.fetch('POSTGRES_PORT') %>

