default: &default
  adapter: postgis # Uses postgis, see guide at https://medium.com/@Evert_Salinas/creating-a-basic-geolocation-search-application-with-postgis-and-rails-part-i-6f7c8985b6da
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_cache: &default_cache
  <<: *default
  adapter: postgresql
  migrations_paths: db/cache_migrate

default_queue: &default_queue
  <<: *default
  adapter: postgresql
  migrations_paths: db/queue_migrate

default_cable: &default_cable
  <<: *default
  adapter: postgresql
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *default
    database: lokaler_lnu_no_development
  cache:
    <<: *default_cache
    database: lokaler_lnu_no_develpment_cache
  queue:
    <<: *default_queue
    database: lokaler_lnu_no_development_queue
  cable:
    <<: *default_cable
    database: lokaler_lnu_no_development_cable

test:
  primary:
    <<: *default
    database: lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>
  cache:
    <<: *default_cache
    database: lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>_cache
  queue:
    <<: *default_queue
    database: lokaler_lnu_no_test<%= ENV['TEST_ENV_NUMBER'] %>_queue

production:
  primary:
    <<: *default
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    database: <%= ENV.fetch("DATABASE_NAME", "lokaler_lnu_no_production") %>
    username: <%= ENV.fetch("DATABASE_USERNAME", "") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  cache:
    <<: *default_cache
    host: <%= ENV.fetch("CACHE_DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("CACHE_DATABASE_PORT", 5432) %>
    database: <%= ENV.fetch("CACHE_DATABASE_NAME", "lokaler_lnu_no_production_cache") %>
    username: <%= ENV.fetch("CACHE_DATABASE_USERNAME", "") %>
    password: <%= ENV.fetch("CACHE_DATABASE_PASSWORD", "") %>
  queue:
    <<: *default_queue
    host: <%= ENV.fetch("QUEUE_DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("QUEUE_DATABASE_PORT", 5432) %>
    database: <%= ENV.fetch("QUEUE_DATABASE_NAME", "lokaler_lnu_no_production_queue") %>
    username: <%= ENV.fetch("QUEUE_DATABASE_USERNAME", "") %>
    password: <%= ENV.fetch("QUEUE_DATABASE_PASSWORD", "") %>
  cable:
    <<: *default_cable
    host: <%= ENV.fetch("CABLE_DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("CABLE_DATABASE_PORT", 5432) %>
    database: <%= ENV.fetch("CABLE_DATABASE_NAME", "lokaler_lnu_no_production_cable") %>
    username: <%= ENV.fetch("CABLE_DATABASE_USERNAME", "") %>
    password: <%= ENV.fetch("CABLE_DATABASE_PASSWORD", "") %>


