# These are only for STAGING
# They will be merged with the common ones in deploy.yml

# Load environment variables from .env file
<%
  require "dotenv"
  Dotenv.load(".env.staging")
%>

# Name of your application. Used to uniquely configure containers.
service: staging
proxy:
  ssl: true
  hosts:
    - lokaler-staging.digitalfrivillighet.no
    - staging.lokaler.lnu.no
env:
  clear:
    RAILS_ENV: staging
    POSTGRES_HOST: staging-db
    POSTGRES_DB: lokaler_lnu_no_staging
    POSTGRES_PORT: 5432
accessories:
  db:
    port: "127.0.0.1:5433:5432"
    env:
      clear:
        POSTGRES_DB: lokaler_lnu_no_staging