# Name of your application. Used to uniquely configure containers.
service: lokaler-lnu-no

# Name of the container image.
image: danieljacksonnor/lokaler-lnu-no

# Deploy to these servers.
servers:
  web:
    - 95.216.137.182
#proxy:
#  ssl: true
#  host: staging.lokaler.lnu.no
registry:
  username: danieljacksonnor
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  clear:
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY
accessories:
  db:
    image: postgis/postgis:15-3.3
    host: 95.216.137.182
    port: 5432
    directories:
      - data:/var/lib/postgresql/data
  cache_db:
    image: postgres:15
    host: 95.216.137.182
    port: 5433
    directories:
      - cache_data:/var/lib/postgresql/data
  queue_db:
    image: postgres:15
    host: 95.216.137.182
    port: 5434
    directories:
      - queue_data:/var/lib/postgresql/data
  cable_db:
    image: postgres:15
    host: 95.216.137.182
    port: 5435
    directories:
      - cable_data:/var/lib/postgresql/data
