# Name of your application. Used to uniquely configure containers.
service: lnu-lokaler

# Name of the container image.
image: danieljacksonnor/lnu-lokaler

# SSH config
ssh:
  user: lokaler

# Deploy to these servers.
servers:
  web:
    - 95.216.137.182 # Hetzner Lokaler 2024 Oct box

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption.
# TODO: Set up when we have domain names set up.
#proxy:
 # ssl: true
 # host: staging.lokaler.lnu.no

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: danieljacksonnor

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY

# Use a persistent storage volume.
volumes:
  - "storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  db:
    image: postgis/postgis:17-3.5
    host: 95.216.137.182
    port: 5432
    env:
      clear:
        POSTGRES_USER: "lokaler"
        POSTGRES_DB: "lokaler_lnu_no_production"
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.4
    host: 95.216.137.182
    port: 6379
    directories:
      - data:/data

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  shell: app exec --interactive --reuse "bash"

