# These are only for STAGING
# They will be merged with the common ones in deploy.yml

# Load environment variables from .env file
<%
  require "dotenv"
  Dotenv.load(".env.staging")
%>

# Name of your application. Used to uniquely configure containers.
service: staging-lokaler-lnu-no
proxy:
  hosts:
    lokaler-staging.digitalfrivillighet.no
    staging.lokaler.lnu.no
env:
  clear:
    POSTGRES_DB: lokaler_lnu_no_staging
accessories:
  db:
    env:
      clear:
        POSTGRES_DB: lokaler_lnu_no_staging