default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "syncing_data"
      priority: 99 # Higher is lower
      threads: 1
      processes: 1
    - queues: "default"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
