name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    # If you need DB like PostgreSQL, Redis then define service below.
    # https://github.com/actions/example-services/tree/master/.github/workflows
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 3.0.3
      PGHOST: localhost
      PGUSER: postgres
      # Rails verifies the time zone in DB is the same as the time zone of the Rails app
      TZ: "Europe/Warsaw"
      MAPBOX_API_KEY: pk.eyJ1IjoibWF0aGlhczIzNCIsImEiOiJja3U1N2o0MGoybGl5MnVxaDcyaHdjZDFpIn0.S-c3HtdhqhyAR6izLxY-iQ

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run Yarn
        run: |
          yarn

      - name: Create DB
        run: |
          cp config/database.yml.example config/database.yml
          bin/rails db:prepare
      - name: Rubocop
        run: |
          bundle exec rubocop
      - name: Run tests
        run: |
          bundle exec rspec
